apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: note-app-keda
  namespace: notes-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notes-app-deployment           # must match your Deployment name
  
  pollingInterval: 30                 # how often to check the metric (seconds)
  cooldownPeriod: 300                 # how long to wait after scale-in activity (seconds)
  
  minReplicaCount: 1                  # minimum pods
  maxReplicaCount: 10                 # maximum pods
  
  triggers:
    - type: cpu                       # use the built-in CPU trigger
      metadata:
        type: Utilization            # scale based on percentage utilization
        value: "50"   
