kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
 name: note-app-vpa
 namespace: notes-app

spec:
 targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notes-app-deployment
 updatePolicy:
   updateMode: "Auto" # "Initial" or "off"